# BOIKWD 
# Lab 5 Indeks Kandalla

## Mikołaj Ogarek Środa 8:00 grupa 1a

In [14]:
#Data
A=[[1,2/3,2,5/2,5/3,5],[3/2,1,3,10/3,3,9],[1/2,1/3,1,4/3,7/8,5/2],[2/5,3/10,3/4,1,5/6,12/5],[3/5,1/3,8/7,6/5,1,3],[1/5,1/9,2/5,5/12,1/3,1]]
B=[[1,2/5,3,7/3,1/2,1,2],[5/2,1,4/7,1,1,3,2/3],[1/3,7/4,1,1/2,2,1/2,1],[3/7,1,2,1,4,2,6],[2,1,1/2,1/4,1,1/2,3/4],[1,1/3,2,1/2,2,1,5/8],[1/2,3/2,1,1/6,4/3,8/5,1]]
C=[[1,2/3,2/15,1,8,12/5,1,1/2],[3/2,1,1,2,1,2/3,1/6,1],[15/2,1,1,5/2,7/8,2,1,1/5],[1,1/2,2/5,1,4/3,1,2/7,1],[1/8,1,8/7,3/4,1,1/5,2/7,1],[5/12,3/2,1/2,1,5,1,3,2],[1,6,1,7/2,7/2,1/3,1,3/11],[2,1,5,1,1,1/2,11/3,1]]
D=[[0,1,1,-1,-1,1,-1],[-1,0,0,1,1,-1,0],[-1,0,0,0,1,1,-1],[1,-1,0,0,1,0,1],[1,0,-1,-1,0,1,-1],[-1,1,-1,1,-1,0,0],[1,0,1,-1,1,0,0]]
E=[[0,1,0,0,-1],[-1,0,0,0,1],[0,0,0,1,0],[0,0,-1,0,0],[1,-1,0,0,0]]
F=[[0,-1,1,-1,1,-1,1,-1,1],[1,0,1,1,1,-1,-1,-1,-1],[-1,-1,0,-1,1,-1,1,1,1],[1,-1,1,0,-1,1,-1,1,-1],[-1,-1,-1,1,0,-1,1,1,1],[1,1,1,-1,1,0,-1,-1,-1],[-1,1,-1,1,-1,1,0,1,-1],[1,1,-1,-1,-1,1,-1,0,1],[-1,1,-1,1,-1,1,1,-1,0]]

#Functions
import numpy as np
def change_matrix_to_generic_tournament(M):
    gen_tournament=[]
    k = len(M[0])
    for i in range(k):
        line=[]
        for j in range(k):
            if M[i][j]>1:
                line.append(1)
            elif M[i][j]<1:
                line.append(-1)
            else:
                line.append(0)
        gen_tournament.append(line)
    
    return(np.array(gen_tournament))

def check_if_matrix_is_generic_tournament(M):
    is_it_generic = True
    k = len(M[0])
    for i in range(k):
        for j in range(k):
            if M[i][j] != -M[j][i]:
                is_it_generic = False
                
    if is_it_generic:
        print("Yes, this matrix is the generic tournament!")
    else:
        print("No, this matrix is not the generic tournament!")
            

def is_draw_possible(M):
    is_possible = False
    k = len(M[0])
    for i in range(k):
        for j in range(k):
            if M[i][j] == 0 and i!=j:
                is_possible = True
                
    if is_possible:
        print("Yes, draw is possible!")
    else:
        print("No, draw is impossible!")
        
def classic_Kandall_index(M):
    Tmi = 0
    n = len(M)
    for i in range(0,n):
        for j in range(i+1,n):
            for k in range(j+1,n):
                
                if M[i][j] == M[j][k] == M[k][i] and i!=k and k!=j:
                    Tmi= Tmi+1z
    In=0
    if n%2==1:
        In = (pow(n,3) - n)/24
    else:
        In = (pow(n,3) - (4*n))/24
    

    
    return (1 - (Tmi/In))

        
                
    
def generic_Kandall_index(M):
    Tmi = 0
    n = len(M[0])
    for i in range(n):
        for j in range(i+1, n):
            for k in range(j+1, n):
                
                if M[i][j] == M[j][k] == M[k][i]!=0 and i!=k!=j:
                    Tmi= Tmi+1
                elif M[i][j] == M[j][k] == 0 and M[k][i]!=0 and i!=k!=j:
                    Tmi= Tmi+1
                elif M[k][i] == M[j][k] == 0 and M[i][j]!=0 and i!=k!=j:
                    Tmi= Tmi+1
                elif M[i][j] == M[k][i] == 0 and M[j][k]!=0 and i!=k!=j:
                    Tmi= Tmi+1
                elif M[i][j] == M[j][k] != 0 and M[k][i]==0 and i!=k!=j:
                    Tmi= Tmi+1
                elif M[k][i] == M[j][k] != 0 and M[i][j]==0 and i!=k!=j:
                    Tmi= Tmi+1
                elif M[i][j] == M[k][i] != 0 and M[j][k]==0 and i!=k!=j:
                    Tmi= Tmi+1
    In=0
    if n%4==0:
        In = ((13*pow(n,3))-(24*pow(n,2))-(16*n))/96
    elif n%4==1:
        In = ((13*pow(n,3))-(24*pow(n,2))-(19*n) +30)/96
    elif n%4==2:
        In = ((13*pow(n,3))-(24*pow(n,2))-(4*n))/96
    else: 
        In = ((13*pow(n,3))-(24*pow(n,2))-(19*n)+18)/96
    

    return (1 - ((Tmi)/In))





In [15]:
print("Matrix A changed to generic tournament: ")
generic_A = change_matrix_to_generic_tournament(A)
print(generic_A)

print("Matrix B changed to generic tournament: ")
generic_B = change_matrix_to_generic_tournament(B)
print(generic_B)

print("Matrix C changed to generic tournament: ")
generic_C = change_matrix_to_generic_tournament(C)
print(generic_C)

Matrix A changed to generic tournament: 
[[ 0 -1  1  1  1  1]
 [ 1  0  1  1  1  1]
 [-1 -1  0  1 -1  1]
 [-1 -1 -1  0 -1  1]
 [-1 -1  1  1  0  1]
 [-1 -1 -1 -1 -1  0]]
Matrix B changed to generic tournament: 
[[ 0 -1  1  1 -1  0  1]
 [ 1  0 -1  0  0  1 -1]
 [-1  1  0 -1  1 -1  0]
 [-1  0  1  0  1  1  1]
 [ 1  0 -1 -1  0 -1 -1]
 [ 0 -1  1 -1  1  0 -1]
 [-1  1  0 -1  1  1  0]]
Matrix C changed to generic tournament: 
[[ 0 -1 -1  0  1  1  0 -1]
 [ 1  0  0  1  0 -1 -1  0]
 [ 1  0  0  1 -1  1  0 -1]
 [ 0 -1 -1  0  1  0 -1  0]
 [-1  0  1 -1  0 -1 -1  0]
 [-1  1 -1  0  1  0  1  1]
 [ 0  1  0  1  1 -1  0 -1]
 [ 1  0  1  0  0 -1  1  0]]


In [16]:
print("This is matrix D")
print(np.array(D))
check_if_matrix_is_generic_tournament(D)

print("This is matrix E")
print(np.array(E))
check_if_matrix_is_generic_tournament(E)

print("This is matrix F")
print(np.array(F))
check_if_matrix_is_generic_tournament(F)

This is matrix D
[[ 0  1  1 -1 -1  1 -1]
 [-1  0  0  1  1 -1  0]
 [-1  0  0  0  1  1 -1]
 [ 1 -1  0  0  1  0  1]
 [ 1  0 -1 -1  0  1 -1]
 [-1  1 -1  1 -1  0  0]
 [ 1  0  1 -1  1  0  0]]
No, this matrix is not the generic tournament!
This is matrix E
[[ 0  1  0  0 -1]
 [-1  0  0  0  1]
 [ 0  0  0  1  0]
 [ 0  0 -1  0  0]
 [ 1 -1  0  0  0]]
Yes, this matrix is the generic tournament!
This is matrix F
[[ 0 -1  1 -1  1 -1  1 -1  1]
 [ 1  0  1  1  1 -1 -1 -1 -1]
 [-1 -1  0 -1  1 -1  1  1  1]
 [ 1 -1  1  0 -1  1 -1  1 -1]
 [-1 -1 -1  1  0 -1  1  1  1]
 [ 1  1  1 -1  1  0 -1 -1 -1]
 [-1  1 -1  1 -1  1  0  1 -1]
 [ 1  1 -1 -1 -1  1 -1  0  1]
 [-1  1 -1  1 -1  1  1 -1  0]]
Yes, this matrix is the generic tournament!


In [17]:
print("Matrix generic A: ")
is_draw_possible(generic_A)

print("Matrix generic B: ")
is_draw_possible(generic_B)

print("Matrix generic C: ")
is_draw_possible(generic_C)

print("Matrix E: ")
is_draw_possible(E)

print("Matrix F: ")
is_draw_possible(F)


Matrix generic A: 
No, draw is impossible!
Matrix generic B: 
Yes, draw is possible!
Matrix generic C: 
Yes, draw is possible!
Matrix E: 
Yes, draw is possible!
Matrix F: 
No, draw is impossible!


In [18]:
print("Generic Kandall index for matrix generic_A: ")
print(generic_Kandall_index(generic_A))

print("Generic Kandall index for matrix generic_B: ")
print(generic_Kandall_index(generic_B))

print("Generic Kandall index for matrix generic_C: ")
print(generic_Kandall_index(generic_C))

print("Generic Kandall index for matrix E: ")
print(generic_Kandall_index(E))

print("Generic Kandall index for matrix F: ")
print(generic_Kandall_index(F))

Generic Kandall index for matrix generic_A: 
1.0
Generic Kandall index for matrix generic_B: 
0.5454545454545454
Generic Kandall index for matrix generic_C: 
0.42307692307692313
Generic Kandall index for matrix E: 
0.0
Generic Kandall index for matrix F: 
0.6103896103896104


In [19]:
print("Classic Kandall index for matrix generic_A: ")
print(classic_Kandall_index(generic_A))

print("Classic Kandall index for matrix F: ")
print(classic_Kandall_index(F))zz



Classic Kandall index for matrix generic_A: 
1.0
Classic Kandall index for matrix F: 
0 1 6
0 1 8
0 2 7
0 3 4
0 3 6
0 3 8
0 4 7
0 5 6
0 5 8
0 6 7
1 2 6
1 2 7
1 2 8
1 3 5
1 3 7
1 4 6
1 4 7
1 4 8
2 3 4
2 3 6
2 3 8
2 5 6
2 5 7
2 5 8
3 4 5
3 7 8
4 5 6
4 5 7
4 5 8
6 7 8
0.0
Classic Kandall index for matrix F: 
0 1 4
0.8
